CREATE OR REPLACE TABLE `crp-sdx-cx-analitica.mus_sdx_cx_adv_analytics_neg_fin_trn.CICD_AAREYESC_FECHAS_COMPRA_SBB_VISA` AS WITH
TABLA0 AS (
SELECT
COALESCE(`crp-pro-cx-analitica.mus_pro_procesos_transformacion.CTA_TRACK`(CTA_CVE),CTA_CVE) AS CTA_TRACK
,CASE WHEN TRN_CVE IN (1,6,101) AND trn_tda_cve IN ("0782") THEN -2
WHEN TRN_CVE IN (1,6,101) THEN -1
ELSE MCC_CVE END AS MCC_CVE
,TRN_FCH_EFE
,TRN_IMP
FROM
`crp-pro-dwh-semanticagold.EIL_DP_VDWH.VFAC_TRN_CRD`
WHERE
TRN_CVE IN (1,6,101,1001, 1101, 2001, 2101) AND TIP_INF IN (200)
AND TRN_FCH_EFE BETWEEN '2024-12-01' AND '2025-12-31' -- ACTUALIZAR LAS FECHAS (12 MESES)
),
TABLA1 AS (
SELECT
*
,DENSE_RANK() OVER (PARTITION BY CTA_TRACK ORDER BY TRN_FCH_EFE, MCC_CVE) AS ORDEN_FECHAS
FROM
TABLA0
)
SELECT
CTA_TRACK
,ORDEN_FECHAS
,MCC_CVE
,MAX(TRN_FCH_EFE) AS FCH_FCH
,SUM(TRN_IMP) AS TRN_IMP
FROM
TABLA1
WHERE
ORDEN_FECHAS <= 3
GROUP BY 1,2,3
;